temas = {
                
        "Atención del Representante": ["atencion", "mala atención", "maltrato", "desatencion", "asistencia", "respuesta", "pesimo", "pésima", "pésimo",
        "no me atienden", "me atendieron mal", "representantes soberbios y maleducados", "destrato total", "atienden sin ganas", "maltrato del empleado", 
        "pésima gestión atención telefónica", "el asesor no tenía ganas de  hablar", "los operadores son  nefastos al momento de explicar", 
        "el operador me atendió de mala gana", "la atencion fue pedante y no resolutiva", "la atención es pésima", "falta de seriedad", 
        "respeto al cliente", "re mala atención", "mala antencion", "la atención es una porquería", "cliente", "clientes", "soy cliente", "no soy cliente",
        "me mude", "mudanza", "cambio de"],
        
        "Precio": ["precio", "caro", "muy caro", "muy alto", "alto", "es caro", "costo alto", "mucho en la factura", "precio alto", 
        "pago mucho", "precios elevados", "muy caro", "carisimo", "es una estafa", "abono elevado", "precios abusivos", 
        "aumentos constantes", "cobrar", "me cobran"],
        
        "Facturación": ["factura", "facturas", "factura vencida", "facturacion", "debito automatico", "cobran", "debitaron",
        "me cobraron dos veces", "factura errónea", "error en facturación", 
        "desorden en la facturación", "facturación desastrosa", "facturación confusa", 
        "reclamo de deuda", "me están reclamando", "cobran lo que quieren", 
        "precio del abono", "importe de la factura", "duplican la facturación",
        "desastres en la facturación", "no respetan precios", 
        "no respetan promociones", "facturan servicios no contratados", 
        "no cumplen lo pactado", "no hacen el descuento", 
        "falta de bonificación", "facturan lo que quieren", 
        "dan de alta servicios que no se piden", "descuento nunca aplicado", 
        "promo sin descuento", "nunca recibí el descuento", "historial", "cambio de", "dar de"],
        
        "Pagos": ["pago virtual", "no puedo pagar", "problemas para pagar", 
        "servicio limitado por falta de pago", "no sé cómo efectuar el pago", 
        "pago virtual y rápida", "debito automático", "cobran mora", 
        "descuentan cuando quieren", "confusa la posibilidad de abonar", 
        "no puedo pagar con débito", "gestión de pago", 
        "homebanking", "no logro pagar", "no se puede pagar", 
        "cobro antes del vencimiento"],
        
        "Atención Técnico": ["técnico", "tecnica", "servicio", "mal servicio", "cita", "demora", "no vino", "no me dieron", 
        "me dejaron", "no tengo", "no me dan", "tardan", "tardaron", "poco serio", "instalacion precaria"],
        
        "Cita Técnica": ["no vinieron", "no me avisaron", "esperé toda la mañana", 
        "me dijeron que reagende", "nunca me lo instalaron", 
        "fueron a otro domicilio", "prometieron día y hora", 
        "ni siquiera aparecieron", "bot avisó horas más tarde", 
        "no cumplieron con la cita", "fallaron en la instalación"],
        
        "Flow": ["flow", "no funciona flow", "nunca pude habilitar flow", "no tengo flow", "streaming", "decodificador", 
        "decodificadores", "control remoto", "guia", "grilla", "canales", "no funciona el control remoto"],
        
        "El Servicio": ["bueno", "buena", "buen", "excelente", "mal servicio", "mal", "desastre", "imposible", "falta de", "debil", "regular", 
        "conforme", "estoy", "no es", "todos son", "sin", "no estoy"],
        
        "IVR": [ "no atienden", "sin atención", "no hay atención",
        "llamás y nadie", "no contestan", "nadie contesta", "nunca me atendieron",
        "no atiende nadie", "nunca atienden", "me cansé de marcar",
        "no puedo comunicarme", "imposible comunicarse", "no me atienden",
        "sistema automático", "una máquina", "hablar con un operador", "representante humano",
        "hablar con una persona", "atención automática", "el menú es", "menú largo", 
        "opciones infinitas", "muchas opciones", "te pasan por opciones", 
        "esperar demasiado", "esperando opciones", "una hora al teléfono", 
        "no me dan la opción", "no identifica el DNI", "no me identifica",
        "llamás y nadie te habla", "siempre la misma grabación"],
        
        "Tiempos de Atención": ["espera de 50 minutos", "una hora al teléfono", "me dejan colgado", 
        "media hora esperando", "esperas 3 hs", "tardan horas", 
        "espera telefónica", "esperando con música", 
        "esperar mucho", "tiempo no vale", "esperando por teléfono"],
        
        "Delivery": [ "nunca me llegó", "no me enviaron", "demoras en la entrega", 
        "esperando la entrega", "no llegó el equipo", 
        "me cobraron y no llegó", "fallaron con la venta", 
        "compra que nunca me llegó", "Andreani", 
        "entrega de un chip", "no enviaron la línea"],
        
                
        "Politica Comercial": ["jubilada", "jubilado", "promo", "promos", "beneficios", "competencia", "precios", 
        "promociones", "descuentos", "descuento", "planes"],
        
        "Funcionamiento del Servicio": ["el servicio es", "días sin servicio", "sin internet", "mala cobertura", "servicio pésimo", "servicio malísimo", "no resuelven los desperfectos técnicos", 
        "muy lento internet", "mal servicio", "nunca me funcionó bien", "servicio irregular",
        "mala velocidad", "mala conexión", "mala señal", "estabilidad", "baja cobertura y alto costo", "el servicio se corta", "el servicio se vive cortando", 
        "problemas con internet y wi fi", "anda mal", "microcortes", "no funciona", "wifi", "se corta", "el servicio funciona con falla", "servicio flojo", "servicio se cae", 
        "mala calidad del servicio", "estuvo funcionando medio mal", "poca señal", "se pixela", 
        "no tengo wi fi", "servicio malísimo", "es un desastre internet", "no tengo tv", "grilla", "canales", "tele", "cortaron el servicio",
        "la velocidad es una mentira", "el servicio se interrumpe constantemente", "decodificador", "decodificadores", "servicio inestable",
        "falencias en el servicio", "cortes frecuentes", "servicio no competitivo", "servicio horrible", "falla mucho", "no es rápido", 
        "servicio se interrumpe muy seguido", "servicio se cuelga", "tecnología vieja", "no tiene suficiente enlace", "streaming", "sigo sin teléfono", 
        "desperfectos técnicos", "no me funciona la fibra", "no llega el wi fi",  
        "no puedo usar flow" "no toma la contraseña", "los canales no tienen buena señal", "cada vez que miro una película se corta", 
        "no es tan veloz como pensaba", "cortan el servicio y está pagado", "se corta la señal", "pésima señal"],
        
        "Resolución": ["no me solucionan", "no resuelven", "no resuelven reclamos", 
        "no puedo resolver", "no toman mi inconveniente", "no me dan información", "complicado resolver", 
        "imposible resolver", "darme una solución", "me pasan de un lado a otro", "tengo que llamar todos los meses", "me siguen dando vueltas", 
        "no hay respuesta", "dan mil vueltas", "mal manejo de reclamos", "no me ayudaron", "no tengo respuesta", 
        "me cortaron y tuve que volver a llamar", "ventas me cortó", "me pasan de un lado al otro", 
        "me transfieren", "me pasen de un lado al otro", "la parte administrativa es de terror", "solucionar", "respuesta", "garantía", "whatsapp", "wsp", "no solucionan", "no resuelven", "reclamos", "resolver problema", 
        "problemas", "inconveniente", "complicado resolverlo", "imposible", "llamar", "dando vueltas", "tardando mucho", "mil vueltas", 
        "mal manejo", "no me ayudan", "ayudaron", "no tengo respuesta", "administrativa", "me cortaron", "volver a llamar", "ventas me cortó", 
        "me cortan", "volvi a llamar", "solución", "historial", "cambio", "dar de"],
        
        "atencion en la venta": ["contratar", "mala experiencia", "contraté", "lo contratado", "no informan bien", "comprar", "condiciones del abono"],
        
        "App/Web/whatssApp": ["whatsapp", "web", "app mi personal", "la app movil", "personal pay", "instagram", "twitter"],
    }